# Generated by Django 4.0.3 on 2022-10-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20, verbose_name='First name')),
                ('lastname', models.CharField(max_length=20, verbose_name='Last name')),
                ('birth_date', models.DateField(verbose_name='Birthday')),
                ('username', models.CharField(max_length=20, verbose_name='Username')),
                ('role', models.CharField(choices=[('CDP', 'Chef de Partie'), ('SC', 'Sous Chef'), ('HC', 'Head Chef')], max_length=3)),
            ],
        ),
    ]
