# Generated by Django 4.0.3 on 2022-10-05 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_alter_employee_options_remove_employee_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_pass',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
