# Generated by Django 4.0.3 on 2022-10-05 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_alter_company_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_pass',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
