# Generated by Django 4.0.3 on 2022-10-07 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_alter_company_company_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'permissions': [('generate_rotas', 'can generate rotas')]},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={},
        ),
    ]
