# Generated by Django 4.0.3 on 2022-10-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0012_alter_company_options_alter_employee_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('KP', 'Kitchen Porter'), ('Commis Chef', 'Commis Chef'), ('CDP', 'Chef de Partie'), ('Sous Chef', 'Sous Chef'), ('Head Chef', 'Head Chef')], max_length=11),
        ),
    ]
