# Generated by Django 4.0.3 on 2022-10-11 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0014_employee_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='days',
            field=models.CharField(default='[1, 1, 1, 1, 1, 1, 1]', max_length=20),
        ),
    ]
