# Generated by Django 4.0.3 on 2022-10-11 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0015_alter_employee_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='days',
        ),
        migrations.AddField(
            model_name='employee',
            name='friday',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='monday',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='saturday',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='sunday',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='thursday',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='tuesday',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='wednesday',
            field=models.IntegerField(default=0),
        ),
    ]
