# Generated by Django 4.0.3 on 2022-10-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0018_employee_company_pass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='company_pass',
            field=models.CharField(default=0, max_length=20, verbose_name='Company Password'),
        ),
    ]
