# Generated by Django 4.0.3 on 2022-10-17 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0019_alter_employee_company_pass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='company_pass',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='register.company'),
        ),
    ]
