# Generated by Django 4.0.3 on 2022-10-17 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0023_alter_employee_comp_pass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='comp_pass',
        ),
    ]
