# Generated by Django 4.0.3 on 2022-10-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0025_remove_employee_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='rotaSaved',
            field=models.BooleanField(default=False),
        ),
    ]
