# Generated by Django 4.0.3 on 2022-10-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0026_company_rotasaved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='rotaSaved',
            field=models.IntegerField(default=0),
        ),
    ]
