# Generated by Django 4.0.3 on 2022-10-19 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0027_alter_company_rotasaved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={},
        ),
    ]
