# Generated by Django 4.0.3 on 2022-10-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0028_alter_company_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='rotaGenerated',
            field=models.IntegerField(default=0),
        ),
    ]
