# Generated by Django 4.0.3 on 2022-10-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0029_company_rotagenerated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='rotaGenerated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='rotaSaved',
            field=models.BooleanField(default=False),
        ),
    ]
