# Generated by Django 4.0.3 on 2022-10-20 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0031_employee_hourly_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='hours_per_week',
            field=models.FloatField(choices=[(5, 5), (10, 10), (15, 15), (20, 20), (25, 25), (30, 30), (35, 35), (40, 40), (45, 45), (50, 50)]),
        ),
    ]
