# Generated by Django 4.0.3 on 2022-11-22 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0039_alter_employee_manager_extendeduser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='postcode',
            field=models.CharField(default=0, max_length=8),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='account',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
