# Generated by Django 4.0.3 on 2022-11-22 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0042_alter_extendeduser_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='user',
            new_name='extended_user',
        ),
    ]
