# Generated by Django 4.0.3 on 2022-11-22 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0043_rename_user_employee_extended_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='first_name',
            field=models.CharField(default=False, max_length=30),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_name',
            field=models.CharField(default=False, max_length=30),
        ),
    ]
